// Original examples for comparison terms outside the A1 headword set.
const extra = (definition, en, vi) => ({ definition, examples: [{ en, vi }] });
export const EXTRA = {
  reply: extra('hồi đáp', 'Please reply to my email.', 'Vui lòng hồi đáp email của tôi.'),
  check: extra('hóa đơn nhà hàng (Mỹ); kiểm tra', 'Could we have the check, please?', 'Cho chúng tôi xin hóa đơn được không?'),
  inexpensive: extra('không đắt', 'This bag is inexpensive and useful.', 'Chiếc túi này không đắt và hữu ích.'),
  notebook: extra('sổ ghi chép', 'Write the new words in your notebook.', 'Viết từ mới vào sổ ghi chép của bạn.'),
  bake: extra('nướng trong lò', 'We bake bread in the oven.', 'Chúng tôi nướng bánh mì trong lò.'),
  costly: extra('tốn kém, gây thiệt hại', 'That mistake was costly.', 'Sai lầm đó gây thiệt hại lớn.'),
  dead: extra('đã chết', 'The plant is dead.', 'Cây đã chết.'),
  available: extra('có sẵn, có thể dùng', 'Is this room available tonight?', 'Phòng này còn trống tối nay không?'),
  receive: extra('nhận', 'We receive a letter every week.', 'Chúng tôi nhận một lá thư mỗi tuần.'),
  glad: extra('vui, mừng', 'I am glad to see you.', 'Tôi vui khi gặp bạn.'),
  hardly: extra('hầu như không', 'I can hardly hear you.', 'Tôi gần như không nghe thấy bạn.'),
  dislike: extra('không thích', 'I dislike this kind of music.', 'Tôi không thích loại nhạc này.'),
  kind: extra('tử tế (tính từ)', 'She is kind to her neighbors.', 'Cô ấy tử tế với hàng xóm.'),
  gift: extra('món quà', 'This gift is for my mother.', 'Món quà này dành cho mẹ tôi.'),
  rest: extra('nghỉ ngơi', 'Sit down and rest for a moment.', 'Ngồi xuống và nghỉ một chút.'),
  yet: extra('chưa; đã ... chưa', 'The bus has not arrived yet.', 'Xe buýt vẫn chưa đến.'),
  powerful: extra('mạnh, có tác động lớn', 'This machine has a powerful engine.', 'Máy này có động cơ mạnh.'),
  certain: extra('chắc chắn', 'I am certain that this is the right address.', 'Tôi chắc đây là địa chỉ đúng.'),
  whether: extra('liệu ... hay không', 'I do not know whether she will come.', 'Tôi không biết liệu cô ấy có đến hay không.'),
  beat: extra('đánh bại', 'Our team beat their team.', 'Đội chúng tôi đánh bại đội của họ.'),
  slowly: extra('một cách chậm rãi', 'Please speak slowly.', 'Vui lòng nói chậm.'),
};

// Select the sense that actually illustrates a particular comparison.
export const COMPARISON_SENSES = {
  'write|type': extra('gõ chữ bằng bàn phím', 'I type my story on a computer.', 'Tôi gõ câu chuyện của mình trên máy tính.'),
  'meet|see': extra('gặp một người', 'I see my friend every weekend.', 'Tôi gặp bạn mình vào mỗi cuối tuần.'),
  'good|well': extra('một cách tốt', 'She sings well.', 'Cô ấy hát hay.'),
  'photo|picture': extra('hình; tranh vẽ hoặc ảnh', 'I draw a picture of my house.', 'Tôi vẽ một bức tranh ngôi nhà của mình.'),
  'tourist|visitor': extra('người đến thăm', 'Our visitor is a friend from another town.', 'Khách đến thăm chúng tôi là một người bạn từ thị trấn khác.'),
};
export const REGISTERS = {
  bike: 'Thân mật', dad: 'Thân mật', mom: 'Thân mật', yeah: 'Thân mật',
  awesome: 'Thân mật', father: 'Trung tính', yes: 'Trung tính', photograph: 'Trung tính',
};

export const IPA_OVERRIDES = {
  'a, an': '/ə, eɪ/; /ən, æn/', 'have to': '/ˈhæf tə/', 'ice cream': '/ˈaɪs kriːm/',
  'next to': '/ˈnɛkst tə/', 'no one': '/ˈnoʊ wʌn/', 'o’clock': '/əˈklɑk/',
  'close1': '/kloʊz/', 'live1': '/lɪv/', 'lie1': '/laɪ/', 'minute1': '/ˈmɪnɪt/',
  object: '/ˈɑbdʒɛkt/', project: '/ˈprɑdʒɛkt/', present: '/ˈprɛzənt/',
  'read': '/riːd/ (hiện tại); /rɛd/ (quá khứ)', 'use': '/juːz/ (động từ)',
  'can1': '/kæn, kən/', 'do1': '/duː/', 'last1 (final)': '/læst/',
  'long1': '/lɔŋ/', 'I': '/aɪ/', i: '/aɪ/',
  'like (find sb/sth pleasant)': '/laɪk/', 'like (similar)': '/laɪk/',
};

// Inflections belong in a separate section, rather than fabricated word-family entries.
export const FORMS = {
  'a, an': 'a=mạo từ trước âm phụ âm;an=mạo từ trước âm nguyên âm',
  be: 'am=hiện tại với I;is=hiện tại số ít;are=hiện tại số nhiều/you;was=quá khứ số ít;were=quá khứ số nhiều/you;been=phân từ;being=dạng -ing',
  i: 'I=tôi (chủ ngữ);me=tôi (tân ngữ);my=của tôi trước danh từ;mine=của tôi khi đi riêng;myself=chính tôi',
  me: 'I=chủ ngữ;me=tân ngữ;my=của tôi;mine=sở hữu đi riêng;myself=phản thân',
  my: 'I=chủ ngữ;me=tân ngữ;my=sở hữu trước danh từ;mine=sở hữu đi riêng;myself=phản thân',
  he: 'he=anh ấy (chủ ngữ);him=anh ấy (tân ngữ);his=của anh ấy;himself=chính anh ấy',
  him: 'he=chủ ngữ;him=tân ngữ;his=sở hữu;himself=phản thân',
  his: 'he=chủ ngữ;him=tân ngữ;his=sở hữu;himself=phản thân',
  she: 'she=cô ấy (chủ ngữ);her=cô ấy (tân ngữ)/của cô ấy;hers=của cô ấy khi đi riêng;herself=chính cô ấy',
  her: 'she=chủ ngữ;her=tân ngữ/sở hữu trước danh từ;hers=sở hữu đi riêng;herself=phản thân',
  it: 'it=nó (chủ ngữ/tân ngữ);its=của nó;itself=chính nó',
  its: 'it=nó (chủ ngữ/tân ngữ);its=của nó;itself=phản thân',
  we: 'we=chúng tôi (chủ ngữ);us=chúng tôi (tân ngữ);our=của chúng tôi trước danh từ;ours=của chúng tôi khi đi riêng;ourselves=chính chúng tôi',
  us: 'we=chủ ngữ;us=tân ngữ;our=sở hữu trước danh từ;ours=sở hữu đi riêng;ourselves=phản thân',
  our: 'we=chủ ngữ;us=tân ngữ;our=sở hữu trước danh từ;ours=sở hữu đi riêng;ourselves=phản thân',
  they: 'they=họ (chủ ngữ);them=họ (tân ngữ);their=của họ trước danh từ;theirs=của họ khi đi riêng;themselves=chính họ',
  them: 'they=chủ ngữ;them=tân ngữ;their=sở hữu trước danh từ;theirs=sở hữu đi riêng;themselves=phản thân',
  their: 'they=chủ ngữ;them=tân ngữ;their=sở hữu trước danh từ;theirs=sở hữu đi riêng;themselves=phản thân',
  you: 'you=bạn/các bạn;your=sở hữu trước danh từ;yours=sở hữu đi riêng;yourself=phản thân số ít;yourselves=phản thân số nhiều',
  your: 'you=chủ ngữ/tân ngữ;your=sở hữu trước danh từ;yours=sở hữu đi riêng;yourself/yourselves=phản thân',
  yourself: 'you=chủ ngữ/tân ngữ;yourself=phản thân số ít;yourselves=phản thân số nhiều',
  this: 'this=này (số ít);these=này (số nhiều)', that: 'that=kia (số ít);those=kia (số nhiều)',
  child: 'child=một trẻ em;children=nhiều trẻ em', person: 'person=một người;people=nhiều người',
  people: 'person=một người;people=nhiều người', man: 'man=một người đàn ông;men=nhiều người đàn ông',
  woman: 'woman=một phụ nữ;women=nhiều phụ nữ', foot: 'foot=một bàn chân;feet=nhiều bàn chân',
  wife: 'wife=một người vợ;wives=nhiều người vợ',
  tooth: 'tooth=một chiếc răng;teeth=nhiều chiếc răng', mouse: 'mouse=một con chuột;mice=nhiều con chuột',
  sheep: 'one sheep=một con cừu;two sheep=hai con cừu',
  'do1': 'do=nguyên mẫu;does=hiện tại ngôi ba số ít;did=quá khứ;done=phân từ;doing=dạng -ing',
  have: 'have=nguyên mẫu/hiện tại;has=hiện tại ngôi ba số ít;had=quá khứ/phân từ;having=dạng -ing',
  go: 'go=nguyên mẫu;went=quá khứ;gone=phân từ;going=dạng -ing',
  come: 'come=nguyên mẫu;came=quá khứ;come=phân từ;coming=dạng -ing',
  get: 'get=nguyên mẫu;got=quá khứ;gotten=phân từ thông dụng Mỹ;getting=dạng -ing',
  eat: 'eat=nguyên mẫu;ate=quá khứ;eaten=phân từ;eating=dạng -ing',
  drink: 'drink=nguyên mẫu;drank=quá khứ;drunk=phân từ;drinking=dạng -ing',
  drive: 'drive=nguyên mẫu;drove=quá khứ;driven=phân từ;driving=dạng -ing',
  write: 'write=nguyên mẫu;wrote=quá khứ;written=phân từ;writing=dạng -ing',
  take: 'take=nguyên mẫu;took=quá khứ;taken=phân từ;taking=dạng -ing',
  give: 'give=nguyên mẫu;gave=quá khứ;given=phân từ;giving=dạng -ing',
  see: 'see=nguyên mẫu;saw=quá khứ;seen=phân từ;seeing=dạng -ing',
  know: 'know=nguyên mẫu;knew=quá khứ;known=phân từ;knowing=dạng -ing',
  'lie1': 'lie=nằm (nguyên mẫu);lay=nằm (quá khứ);lain=nằm (phân từ);lying=dạng -ing',
  sit: 'sit=nguyên mẫu;sat=quá khứ/phân từ;sitting=dạng -ing',
  stand: 'stand=nguyên mẫu;stood=quá khứ/phân từ;standing=dạng -ing',
  swim: 'swim=nguyên mẫu;swam=quá khứ;swum=phân từ;swimming=dạng -ing',
  run: 'run=nguyên mẫu;ran=quá khứ;run=phân từ;running=dạng -ing',
  buy: 'buy=nguyên mẫu;bought=quá khứ/phân từ;buying=dạng -ing',
  bring: 'bring=nguyên mẫu;brought=quá khứ/phân từ;bringing=dạng -ing',
  teach: 'teach=nguyên mẫu;taught=quá khứ/phân từ;teaching=dạng -ing',
  think: 'think=nguyên mẫu;thought=quá khứ/phân từ;thinking=dạng -ing',
  sell: 'sell=nguyên mẫu;sold=quá khứ/phân từ;selling=dạng -ing',
  send: 'send=nguyên mẫu;sent=quá khứ/phân từ;sending=dạng -ing',
  pay: 'pay=nguyên mẫu;paid=quá khứ/phân từ;paying=dạng -ing',
  make: 'make=nguyên mẫu;made=quá khứ/phân từ;making=dạng -ing',
  say: 'say=nguyên mẫu;said=quá khứ/phân từ;saying=dạng -ing',
  tell: 'tell=nguyên mẫu;told=quá khứ/phân từ;telling=dạng -ing',
  speak: 'speak=nguyên mẫu;spoke=quá khứ;spoken=phân từ;speaking=dạng -ing',
  'read': 'read /riːd/=hiện tại;read /rɛd/=quá khứ/phân từ;reading=dạng -ing',
  wear: 'wear=nguyên mẫu;wore=quá khứ;worn=phân từ;wearing=dạng -ing',
  wake: 'wake=nguyên mẫu;woke=quá khứ;woken=phân từ;waking=dạng -ing',
  break: 'break=nguyên mẫu;broke=quá khứ;broken=phân từ;breaking=dạng -ing',
  begin: 'begin=nguyên mẫu;began=quá khứ;begun=phân từ;beginning=dạng -ing',
  grow: 'grow=nguyên mẫu;grew=quá khứ;grown=phân từ;growing=dạng -ing',
  fall: 'fall=nguyên mẫu;fell=quá khứ;fallen=phân từ;falling=dạng -ing',
  choose: 'choose=nguyên mẫu;chose=quá khứ;chosen=phân từ;choosing=dạng -ing',
  forget: 'forget=nguyên mẫu;forgot=quá khứ;forgotten=phân từ;forgetting=dạng -ing',
  fly: 'fly=nguyên mẫu;flew=quá khứ;flown=phân từ;flying=dạng -ing',
  draw: 'draw=nguyên mẫu;drew=quá khứ;drawn=phân từ;drawing=dạng -ing',
  find: 'find=nguyên mẫu;found=quá khứ/phân từ;finding=dạng -ing',
  feel: 'feel=nguyên mẫu;felt=quá khứ/phân từ;feeling=dạng -ing',
  hear: 'hear=nguyên mẫu;heard=quá khứ/phân từ;hearing=dạng -ing',
  leave: 'leave=nguyên mẫu;left=quá khứ/phân từ;leaving=dạng -ing',
  lose: 'lose=nguyên mẫu;lost=quá khứ/phân từ;losing=dạng -ing',
  keep: 'keep=nguyên mẫu;kept=quá khứ/phân từ;keeping=dạng -ing',
  meet: 'meet=nguyên mẫu;met=quá khứ/phân từ;meeting=dạng -ing',
  mean: 'mean=nguyên mẫu;meant=quá khứ/phân từ;meaning=dạng -ing',
  sleep: 'sleep=nguyên mẫu;slept=quá khứ/phân từ;sleeping=dạng -ing',
  spend: 'spend=nguyên mẫu;spent=quá khứ/phân từ;spending=dạng -ing',
  understand: 'understand=nguyên mẫu;understood=quá khứ/phân từ;understanding=dạng -ing',
  win: 'win=nguyên mẫu;won=quá khứ/phân từ;winning=dạng -ing',
  build: 'build=nguyên mẫu;built=quá khứ/phân từ;building=dạng -ing',
  cut: 'cut=nguyên mẫu/quá khứ/phân từ;cutting=dạng -ing',
  cost: 'cost=nguyên mẫu/quá khứ/phân từ trong nghĩa có giá;costing=dạng -ing',
  let: 'let=nguyên mẫu/quá khứ/phân từ;letting=dạng -ing',
  put: 'put=nguyên mẫu/quá khứ/phân từ;putting=dạng -ing',
};
