// Hand-written pronunciation corrections, irregular forms and comparison senses.
export const IPA_OVERRIDES = {
  'close2': '/kloʊs/', combine: '/kəmˈbaɪn/', 'content1': '/ˈkɑntɛnt/',
  contrast: '/ˈkɑntræst/ (n.); /kənˈtræst/ (v.)', current: '/ˈkɝənt/', discount: '/ˈdɪskaʊnt/',
  export: '/ˈɛkspɔrt/ (n.); /ɪkˈspɔrt/ (v.)',
  graduate: '/ˈɡrædʒuət/ (n.); /ˈɡrædʒueɪt/ (v.)',
  hurricane: '/ˈhɝɪkeɪn/', import: '/ˈɪmpɔrt/ (n.); /ɪmˈpɔrt/ (v.)',
  it: '/ˌaɪ ˈtiː/', 'lead1': '/liːd/', 'live2': '/laɪv/', located: '/ˈloʊkeɪtɪd/',
  reject: '/rɪˈdʒɛkt/', separate: '/ˈsɛpəreɪt/', spring: '/sprɪŋ/',
  transport: '/trænsˈpɔrt/', used1: '/juːzd/', used2: '/juːst/', will: '/wɪl/',
  breath: '/brɛθ/', breathe: '/briːð/',
};
export const FORMS = {
  analysis: 'analyses=dạng số nhiều của analysis',
  basis: 'bases=dạng số nhiều của basis',
  ban: 'banned=quá khứ/phân từ của ban;banning=dạng -ing của ban',
  bend: 'bent=quá khứ và phân từ của bend;bending=dạng -ing',
  bite: 'bit=quá khứ của bite;bitten=phân từ của bite;biting=dạng -ing',
  'bank (river)': 'banks=các bờ sông',
  breath: 'breaths=các lần hít thở',
  breathe: 'breathed=quá khứ/phân từ;breathing=dạng -ing',
  bury: 'buried=quá khứ/phân từ của bury;burying=dạng -ing',
  cloth: 'cloths=những miếng vải (khác clothes là quần áo)',
  commit: 'committed=quá khứ/phân từ của commit;committing=dạng -ing',
  freeze: 'froze=quá khứ của freeze;frozen=phân từ của freeze;freezing=dạng -ing',
  further: 'furthest=dạng chỉ mức xa nhất trong một số ngữ cảnh',
  gentleman: 'gentlemen=dạng số nhiều của gentleman',
  hang: 'hung=quá khứ/phân từ thông dụng của hang;hanging=dạng -ing',
  lay: 'laid=quá khứ/phân từ của lay;laying=dạng -ing',
  leaf: 'leaves=dạng số nhiều của leaf',
  'lie2 (tell a lie)': 'lied=quá khứ/phân từ của lie nghĩa nói dối;lying=dạng -ing',
  need: "needn't=không cần (need not)",
  ought: 'ought to=nên;ought not to=không nên',
  ours: 'our=từ hạn định sở hữu, phải đi với danh từ',
  quit: 'quit=quá khứ/phân từ thường dùng trong tiếng Anh Mỹ;quitting=dạng -ing',
  roll: 'rolled=quá khứ/phân từ;rolling=dạng -ing',
  'row1': 'rows=các hàng, dãy',
  'set (group)': 'sets=các bộ, tập hợp',
  'set (put)': 'set=quá khứ và phân từ giữ nguyên;setting=dạng -ing',
  shelf: 'shelves=dạng số nhiều của shelf',
  shine: 'shone=quá khứ/phân từ trong nhiều cách dùng;shined=biến thể, thường dùng khi đánh bóng;shining=dạng -ing',
  shoot: 'shot=quá khứ/phân từ của shoot;shooting=dạng -ing',
  sink: 'sank=quá khứ của sink;sunk=phân từ của sink;sinking=dạng -ing',
  spread: 'spread=quá khứ và phân từ giữ nguyên;spreading=dạng -ing',
  spring: 'sprang=quá khứ; sprung=biến thể quá khứ và phân từ;springing=dạng -ing',
  'stick (piece of wood)': 'sticks=các cây gậy, que',
  'stick (push into/attach)': 'stuck=quá khứ/phân từ của stick;sticking=dạng -ing',
  theirs: 'their=từ hạn định sở hữu, phải đi với danh từ',
  upset: 'upset=quá khứ/phân từ giữ nguyên;upsetting=dạng -ing',
  young: 'the young=người trẻ nói chung;young=con non (danh từ tập hợp)',
};
const extra = (term, definition, en, vi) => ({ term, definition, examples: [{ en, vi }] });
export const EXTRA = {
  surprised: extra('surprised', 'ngạc nhiên', 'I was surprised to see her.', 'Tôi ngạc nhiên khi gặp cô ấy.'),
  comfortable: extra('comfortable', 'thoải mái', 'This chair is comfortable.', 'Chiếc ghế này thoải mái.'),
  although: extra('although', 'mặc dù (trước mệnh đề)', 'Although it rained, we went out.', 'Dù trời mưa, chúng tôi vẫn ra ngoài.'),
  lie: extra('lie (nằm)', 'nằm, nằm xuống', 'Lie on the bed and rest.', 'Hãy nằm lên giường và nghỉ ngơi.'),
  attend: extra('attend', 'tham dự, có mặt', 'I attended the meeting yesterday.', 'Tôi tham dự cuộc họp hôm qua.'),
  fit: extra('fit', 'vừa kích cỡ', 'These shoes fit me well.', 'Đôi giày này vừa chân tôi.'),
  confusing: extra('confusing', 'gây bối rối, khó hiểu', 'The map is confusing.', 'Bản đồ khó hiểu.'),
  economical: extra('economical', 'tiết kiệm chi phí hoặc nguồn lực', 'This small car is economical to run.', 'Chiếc xe nhỏ này có chi phí vận hành tiết kiệm.'),
  efficient: extra('efficient', 'hiệu quả với ít lãng phí', 'The new machine is fast and efficient.', 'Máy mới nhanh và ít lãng phí nguồn lực.'),
  sincere: extra('sincere', 'chân thành', 'She gave a sincere apology.', 'Cô ấy đưa ra lời xin lỗi chân thành.'),
  alone: extra('alone', 'một mình, không có người khác bên cạnh', 'I enjoy walking alone.', 'Tôi thích đi bộ một mình.'),
  venomous: extra('venomous', 'có nọc độc truyền qua cắn hoặc chích', 'Some snakes are venomous.', 'Một số loài rắn có nọc độc.'),
  principle: extra('principle', 'nguyên tắc', 'Fairness is an important principle.', 'Công bằng là một nguyên tắc quan trọng.'),
  sensitive: extra('sensitive', 'nhạy cảm, dễ bị ảnh hưởng', 'My skin is sensitive to the sun.', 'Da tôi nhạy cảm với ánh nắng.'),
  certainly: extra('certainly', 'chắc chắn; tất nhiên', 'I will certainly call you tomorrow.', 'Tôi chắc chắn sẽ gọi bạn ngày mai.'),
  interpret: extra('interpret', 'phiên dịch; diễn giải', 'She interprets for visitors at the meeting.', 'Cô ấy phiên dịch cho khách tại cuộc họp.'),
  weight: extra('weight', 'trọng lượng', 'The weight of the bag is five kilos.', 'Trọng lượng của túi là năm ki-lô-gam.'),
  worthy: extra('worthy', 'xứng đáng', 'Her work is worthy of praise.', 'Công việc của cô ấy đáng được khen ngợi.'),
  used1: extra('used (đồ đã qua sử dụng)', 'đã qua sử dụng', 'I bought a used bicycle.', 'Tôi mua một chiếc xe đạp đã qua sử dụng.'),
  used2: extra('be used to', 'quen với', 'I am used to getting up early.', 'Tôi đã quen với việc dậy sớm.'),
};
const usedReference = { title: 'Cambridge: used to / be used to', url: 'https://dictionary.cambridge.org/grammar/british-grammar/used-to' };
const historicReference = { title: 'Cambridge: historic / historical', url: 'https://dictionary.cambridge.org/grammar/british-grammar/historic-or-historical' };
export const REFERENCES = {
  used1: [usedReference], used2: [usedReference],
  historic: [historicReference], historical: [historicReference],
  it: [{ title: 'Cambridge: IT', url: 'https://dictionary.cambridge.org/dictionary/english/it' }],
  sensible: [{ title: 'Cambridge: sensible', url: 'https://dictionary.cambridge.org/us/dictionary/english/sensible?topic=aware' }],
  ton: [{ title: 'NIST: ton và metric ton', url: 'https://www.nist.gov/pml/special-publication-811/nist-guide-si-appendix-b-conversion-factors/nist-guide-si-appendix-b9' }],
};
